#include "cmd.h"
#include "IBCM.H"

int main(void)
{
    /* Values are generated by Microsoft's original MKCMD parser from
     * opuscmd.cmd.  On x64 these are offsets in the expanded native symbol
     * table; IBCM remains the original compatibility-map index. */
    if (bcmCut != 2252 || bcmCopy != 2274)
        return 1;
    if (ibcmEditCut != 86 || ibcmEditCopy != 87)
        return 2;
    if (bcmMacStd != 11247)
        return 3;
    return 0;
}
