#include "cmd.h"
#include "IBCM.H"

int main(void)
{
    /* Values are generated by Microsoft's original MKCMD implementation
     * from opuscmd.cmd and the checked-in ibcm.rel compatibility map. */
    if (bcmCut != 1686 || bcmCopy != 1702)
        return 1;
    if (ibcmEditCut != 86 || ibcmEditCopy != 87)
        return 2;
    if (bcmMacStd != 8295)
        return 3;
    return 0;
}
